# DEVELOPMENT ENVIRONMENT
# use the latest version of the docker-compose syntax

version: '3.9'

# List of all services for the development environment
# things like the actual app, the database, the proxy, 
# and any other software the app needs to run go here

services:
  database:
    image: mariadb
    ports: 
      - ${DB_PORT:-3306}:${DB_PORT:-3306}
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-somerootpass}
      - MYSQL_DATABASE=${DB_NAME:-dev}
      - MYSQL_USER=${DB_USER:-myapp}
      - MYSQL_PASSWORD=${DB_PASS:-mypassword}
    networks:
      - traefik

  traefik:
    image: traefik
    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.debug=true"
      - "--log.level=DEBUG"

      - "--providers.docker"
      - "--providers.docker.watch"
      - "--providers.docker.exposedByDefault=false"

      - "--entrypoints.web.address=:${PROXY_HTTP_PORT:-80}"
    networks:
      - traefik
      - inbound
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - target: 80
        published: 80
        mode: host
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.traefik.rule=Host(`${PROXY_HOST}`)"
    - "traefik.http.routers.traefik.service=api@internal"
    - "traefik.http.routers.traefik.entrypoints=web"
    - "traefik.http.services.traefik.loadbalancer.server.port=888"

volumes:
  db-data: {}

networks:
  traefik: 
    name: traefik
  inbound: {}
