name: Django CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    services:
      mariadb:
        image: mariadb
        env:
          MYSQL_ROOT_PASSWORD: somerootpassword
          MYSQL_DATABASE: ci
        ports: ['3306:3306']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migrations
      run: |
        python app/manage.py migrate
        python app/manage.py collectstatic --noinput
      env: 
        DBENGINE: django.db.backends.mysql
        DB_NAME: ci
        DB_USER: root
        DB_PASS: somerootpassword
        DB_HOST: 127.0.0.1
        DB_PORT: ${{ job.services.mariadb.ports[3306] }}
        SECRET_KEY: testkey
    - name: Run Tests
      run: |
        cd app
        pytest --cov
      env: 
        DBENGINE: django.db.backends.mysql
        DB_NAME: ci
        DB_USER: root
        DB_PASS: somerootpassword
        DB_HOST: 127.0.0.1
        DB_PORT: ${{ job.services.mariadb.ports[3306] }}
        SECRET_KEY: testkey